
int bang(int);
int test_bang(int);
int bitCount(int);
int test_bitCount(int);
int bitOr(int, int);
int test_bitOr(int, int);
int bitRepeat(int, int);
int test_bitRepeat(int, int);
int fitsBits(int, int);
int test_fitsBits(int, int);
int getByte(int, int);
int test_getByte(int, int);
int isLessOrEqual(int, int);
int test_isLessOrEqual(int, int);
int isPositive(int);
int test_isPositive(int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int tmin();
int test_tmin();
